[package]
name = "polkadot-primitives-test-helpers"
version = "0.9.13"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"

[dependencies]
sp-application-crypto = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "master" }
# sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }
polkadot-primitives = { path = "../" }
