[package]
name = "polkadot-primitives-test-helpers"
version = "0.9.13"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"

[dependencies]
sp-application-crypto = { git = "https://github.com/paritytech/substrate", branch = "master", default-features = false }
sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "master" }
polkadot-primitives = { path = "../" }


[features]
default = ["std"]
std = [
    "polkadot-primitives/std",
	"sp-application-crypto/std",
]
